ci: Simplify reading vars.yml in publish-nix-pgupgrade-* workflows
This was already a little convoluted and will only get more so in the
following commits but it doesn't have to be that way with a little git
and shell (low tier) magic.

diff --git a/.github/workflows/publish-nix-pgupgrade-scripts.yml b/.github/workflows/publish-nix-pgupgrade-scripts.yml
--- a/.github/workflows/publish-nix-pgupgrade-scripts.yml
+++ b/.github/workflows/publish-nix-pgupgrade-scripts.yml
@@ -30,18 +30,14 @@ jobs:
       - name: Set PostgreSQL versions
         id: set-versions
         env:
-          POSTGRES_VERSION: ${{ inputs.postgresVersion }}
+          rev: ${{ inputs.postgresVersion || 'HEAD' }}
         run: |
-          set -eo pipefail
-          if [[ -n "$POSTGRES_VERSION" ]]; then
-            git rev-parse --verify "$POSTGRES_VERSION" || {
-              echo "Error: git tag '$POSTGRES_VERSION' not found"
-              exit 1
-            }
-            VERSIONS=$(git show "$POSTGRES_VERSION:ansible/vars.yml" | nix run nixpkgs#yq-go -- -o=json -I=0 '.postgres_major')
-          else
-            VERSIONS=$(nix run nixpkgs#yq-go -- -o=json -I=0 '.postgres_major' ansible/vars.yml)
+          set -euo pipefail
+          if ! git rev-parse --verify "$rev"; then
+            echo "Error: git revision '$rev' not found"
+            exit 1
           fi
+          VERSIONS=$(git show "$rev:ansible/vars.yml" | nix run nixpkgs#yq-go -- -o=json -I=0 '.postgres_major')
           echo "postgres_versions=$VERSIONS" >> $GITHUB_OUTPUT
 
   publish-staging:
@@ -60,14 +56,14 @@ jobs:
       - name: Grab release version
         id: process_release_version
         env:
-          POSTGRES_VERSION: ${{ inputs.postgresVersion }}
+          rev: ${{ inputs.postgresVersion || 'HEAD' }}
         run: |
-          set -eo pipefail
-          if [[ -n "$POSTGRES_VERSION" ]]; then
-            VERSION=$(git show "$POSTGRES_VERSION:ansible/vars.yml" | nix run nixpkgs#yq-go -- -r '.postgres_release["postgres'${{ matrix.postgres_version }}'"]')
-          else
-            VERSION=$(nix run nixpkgs#yq-go -- -r '.postgres_release["postgres'${{ matrix.postgres_version }}'"]' ansible/vars.yml)
+          set -euo pipefail
+          if ! git rev-parse --verify "$rev"; then
+            echo "Error: git revision '$rev' not found"
+            exit 1
           fi
+          VERSION=$(git show "$rev:ansible/vars.yml" | nix run nixpkgs#yq-go -- -r '.postgres_release["postgres'${{ matrix.postgres_version }}'"]')
           echo "version=$VERSION" >> "$GITHUB_OUTPUT"
 
       - name: Create a tarball containing pg_upgrade scripts
@@ -115,14 +111,14 @@ jobs:
       - name: Grab release version
         id: process_release_version
         env:
-          POSTGRES_VERSION: ${{ inputs.postgresVersion }}
+          rev: ${{ inputs.postgresVersion || 'HEAD' }}
         run: |
-          set -eo pipefail
-          if [[ -n "$POSTGRES_VERSION" ]]; then
-            VERSION=$(git show "$POSTGRES_VERSION:ansible/vars.yml" | nix run nixpkgs#yq-go -- -r '.postgres_release["postgres'${{ matrix.postgres_version }}'"]')
-          else
-            VERSION=$(nix run nixpkgs#yq-go -- -r '.postgres_release["postgres'${{ matrix.postgres_version }}'"]' ansible/vars.yml)
+          set -euo pipefail
+          if ! git rev-parse --verify "$rev"; then
+            echo "Error: git revision '$rev' not found"
+            exit 1
           fi
+          VERSION=$(git show "$rev:ansible/vars.yml" | nix run nixpkgs#yq-go -- -r '.postgres_release["postgres'${{ matrix.postgres_version }}'"]')
           echo "version=$VERSION" >> "$GITHUB_OUTPUT"
 
       - name: Create a tarball containing pg_upgrade scripts
