fix: rewire postgresVersion input in pg_upgrade publish workflows

diff --git a/.github/workflows/publish-nix-pgupgrade-bin-flake-version.yml b/.github/workflows/publish-nix-pgupgrade-bin-flake-version.yml
--- a/.github/workflows/publish-nix-pgupgrade-bin-flake-version.yml
+++ b/.github/workflows/publish-nix-pgupgrade-bin-flake-version.yml
@@ -23,8 +23,19 @@ jobs:
 
       - name: Set PostgreSQL versions
         id: set-versions
+        env:
+          POSTGRES_VERSION: ${{ inputs.postgresVersion }}
         run: |
-          VERSIONS=$(nix run nixpkgs#yq-go -- -o=json -I=0 '.postgres_major' ansible/vars.yml)
+          set -eo pipefail
+          if [[ -n "$POSTGRES_VERSION" ]]; then
+            git rev-parse --verify "$POSTGRES_VERSION" || {
+              echo "Error: git tag '$POSTGRES_VERSION' not found"
+              exit 1
+            }
+            VERSIONS=$(git show "$POSTGRES_VERSION:ansible/vars.yml" | nix run nixpkgs#yq-go -- -o=json -I=0 '.postgres_major')
+          else
+            VERSIONS=$(nix run nixpkgs#yq-go -- -o=json -I=0 '.postgres_major' ansible/vars.yml)
+          fi
           echo "postgres_versions=$VERSIONS" >> $GITHUB_OUTPUT
 
   publish-staging:
@@ -42,8 +53,15 @@ jobs:
 
       - name: Grab release version
         id: process_release_version
+        env:
+          POSTGRES_VERSION: ${{ inputs.postgresVersion }}
         run: |
-          VERSION=$(nix run nixpkgs#yq-go -- -r '.postgres_release["postgres'${{ matrix.postgres_version }}'"]' ansible/vars.yml)
+          set -eo pipefail
+          if [[ -n "$POSTGRES_VERSION" ]]; then
+            VERSION=$(git show "$POSTGRES_VERSION:ansible/vars.yml" | nix run nixpkgs#yq-go -- -r '.postgres_release["postgres'${{ matrix.postgres_version }}'"]')
+          else
+            VERSION=$(nix run nixpkgs#yq-go -- -r '.postgres_release["postgres'${{ matrix.postgres_version }}'"]' ansible/vars.yml)
+          fi
           echo "version=$VERSION" >> "$GITHUB_OUTPUT"
           echo "major_version=$(echo $VERSION | cut -d'.' -f1)" >> "$GITHUB_OUTPUT"
 
@@ -92,8 +110,15 @@ jobs:
 
       - name: Grab release version
         id: process_release_version
+        env:
+          POSTGRES_VERSION: ${{ inputs.postgresVersion }}
         run: |
-          VERSION=$(nix run nixpkgs#yq-go -- -r '.postgres_release["postgres'${{ matrix.postgres_version }}'"]' ansible/vars.yml)
+          set -eo pipefail
+          if [[ -n "$POSTGRES_VERSION" ]]; then
+            VERSION=$(git show "$POSTGRES_VERSION:ansible/vars.yml" | nix run nixpkgs#yq-go -- -r '.postgres_release["postgres'${{ matrix.postgres_version }}'"]')
+          else
+            VERSION=$(nix run nixpkgs#yq-go -- -r '.postgres_release["postgres'${{ matrix.postgres_version }}'"]' ansible/vars.yml)
+          fi
           echo "version=$VERSION" >> "$GITHUB_OUTPUT"
           echo "major_version=$(echo $VERSION | cut -d'.' -f1)" >> "$GITHUB_OUTPUT"
 
