chore: ship logs to file

diff --git a/.github/workflows/testinfra.yml b/.github/workflows/testinfra.yml
--- a/.github/workflows/testinfra.yml
+++ b/.github/workflows/testinfra.yml
@@ -27,7 +27,12 @@ jobs:
         run: |
           # TODO: use poetry for pkg mgmt
           pip3 install boto3 boto3-stubs[essential] docker ec2instanceconnectcli pytest pytest-testinfra[paramiko,docker] requests
-          pytest -vv -s testinfra/test_all_in_one.py
+          pytest -vv testinfra/test_all_in_one.py
+
+          # show logs if tests failed
+          if [ $? -ne 0 ]; then
+            cat testinfra/testinfra-aio-container-logs.log
+          fi
 
   test-ami:
     strategy:
